### ISSUE TITLE
Error: this.storedLists.get is not a function, with enabled cache

### ISSUE THREAD

**Issue by r15ch13** [felipecaputo/git-project-manager#44]
GPM Version 1.2.0

- fresh start of VSCode and `storeRepositoriesBetweenSessions` is set to `true`
- ctrl+alt+p
- nothing happens
- ctrl+alt+p again
- error

![gpm-load-with-cache](https://cloud.githubusercontent.com/assets/432127/24081508/7e589084-0cb5-11e7-9bf1-c5b802aa091e.gif)

Edit:

- fresh start of VSCode
- `gpm: refresh projects`
- `project list refreshed` appears immediately in the statusbar
- ctrl+alt+p > error
- `gpm: refresh projects` again
- now it really refreshs the list
- ctrl+alt+p > works

**Comment by felipecaputo** [comment]
Hi @r15ch13, I've found the issue.

After the refactoring, the Map that now stores the list was left aside. 

I'll work on it as soon as I get home

Thanks for the feedback

**Comment by felipecaputo** [comment]
Hi there @r15ch13! Could you please validate if everything works fine in 1.2.1? 

If not, let me know

**Comment by r15ch13** [comment]
Works great, thanks 👍
