### ISSUE TITLE
Add depth limit configuration option

### ISSUE THREAD

**Issue by martinpengellyphillips** [felipecaputo/git-project-manager#2]

**Comment by felipecaputo** [comment]
Version 0.1.5 released

**Comment by martinpengellyphillips** [comment]
Thanks for this, but I didn't see any performance boost. Looking at master I see the `filterDir` code commented out - is that intentional / in the release?

https://github.com/felipecaputo/git-project-manager/blob/master/src/gitProjectLocator.js#L53

Also, I think the max depth might work better if the search didn't have to recurse into the `.git` directory to find it. Instead it would check each directory for a subdirectory of `.git`. This would allow a depth of `1` to very quickly find projects that are all stored under a common directory without having to also specify the configuration to exclude folders like `node_modules`.

**Comment by felipecaputo** [comment]
@martinpengellyphillips Sorry for that, I forgot that vcse publishs the local code instead of commited code. I Will fix that ASAP.

And I will make the .`git` fix in the same release

**Comment by felipecaputo** [comment]
Solved in 0.1.6.

Sorry again @martinpengellyphillips, but now i think it is working fine

**Comment by martinpengellyphillips** [comment]
Thanks for the quick update!

Since updating to 0.1.6 the extension breaks for me with the following error:

```
threadService.ts:199 [Plugin Host] WARNING: Promise with no error callback:67
threadService.ts:199 [Plugin Host] Object {exception: null, error: Object, promise: Object, id: 67}
threadService.ts:199 [Plugin Host] WARNING: Promise with no error callback:68
threadService.ts:199 [Plugin Host] Object {exception: null, error: Object, promise: Object, id: 68}
shell.ts:480 An unknown error occurred. Please consult the log for more details.e.onUnexpectedError @ shell.ts:480(anonymous function) @ shell.ts:342e.onUnexpectedError @ errors.ts:72u @ errors.ts:87e.onUnexpectedPluginHostError @ extHost.api.impl.ts:469e.handle @ abstractThreadService.ts:100c @ ipcRemoteCom.ts:172f @ ipcRemoteCom.ts:120doNTCallback0 @ node.js:420_tickCallback @ node.js:349
shell.ts:480 e.text.substr is not a function: TypeError: e.text.substr is not a function
    at e.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:41:17181)
    at e.doElement (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:39:17966)
    at e.li (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:39:17235)
    at e.renderMessage (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:41:16405)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:41:16181
    at Array.forEach (native)
    at e.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:41:16157)
    at e.doElement (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:39:17966)
    at e.ul (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:39:17111)
    at e.renderMessages (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:41:16022)
```

I'll pull master locally and try to debug this further unless it is something you have seen already?

**Comment by felipecaputo** [comment]
In debug the error is not happening, I'm trying to figure it out. Any help is welcome

**Comment by felipecaputo** [comment]
VSCE does not manage well dependencies of dependencies :(

I've figured it out in the worst way, but fixed now in 0.1.9

Sorry for the inconvenience @martinpengellyphillips

**Comment by martinpengellyphillips** [comment]
Works! Thanks.

One thing about max depth - I think it would be best if the max depth check is inclusive rather than the current exclusive (now that the `.git` subfolder check is performed):

```javascript
 return (maxDepth > 0) && ((currentDepth - initialDepth) > maxDepth);
```
to
```javascript
 return (maxDepth > 0) && ((currentDepth - initialDepth) >= maxDepth);
```
This would then ensure that the common case of projects directly under projects base path is handled efficiently. At present I have set the config option to `0.5` as a workaround.

Thanks again!

**Comment by martinpengellyphillips** [comment]
Nevermind my last comment - max depth does work as expected!

**Comment by felipecaputo** [comment]
What do you think about get the origin being optional? There isn't a real necessity for that, was just an idea of handling cases with projects with the same name but, the label is the path itself so, we can let the repo origin configurable.

**Comment by martinpengellyphillips** [comment]
Yeah - I think that would make sense. For me, the main thing about this extension was to reuse the fact I have `.git` for all my projects already, so it is a great way to discover projects quickly. I don't really care that much about the origin when looking for a project - I would drop it altogether ;-)

On that note, it might be good to also consider putting the project name first and then the path after (perhaps like you had origin). 

```
project-a /full/path/to/groupa/projects
project-b /full/path/to/groupa/projects
project-c /full/path/to/groupb/projects
```

This would make the most important information (project name) more visible. 

I guess doing that could also help with filtering if name is considered first and then you can narrow down based on path name. So in the following (contrived) example, you would only have to type `a` rather than `artis` to select the first project:

```
/Users/martin/projects/artisan
/Users/martin/projects/bett
/Users/martin/projects/bungle
```

**Comment by felipecaputo** [comment]
@martinpengellyphillips I've added the configuration to disable the check remote origin, sorry for taking too much time but last sprint was hard to finish

**Comment by martinpengellyphillips** [comment]
Thanks @felipecaputo ! This works perfectly - with `storeRepositoriesBetweenSessions` set to *false*, `maxDepthRecursion` set to *1* and `checkRemoteOrigin` set to *false*, my large list of projects over three roots loads instantly whereas before it would take up to a minute. Thanks again for being so responsive.
